#!/usr/bin/env bash

docker_create_volume(){
  run "docker volume create --name $DOCKER_VOLUME"
}

docker_build_image(){
  run "docker build . -t $DOCKER_IMAGE -f Dockerfile"
}

docker_debug(){
  run "docker run \
    --interactive \
    --tty \
    --rm \
    -e 'TERM=xterm-256color' \
    -v $DOCKER_VOLUME:/mnt/steam/ \
    --entrypoint /bin/bash
    $DOCKER_IMAGE \
    $1"
}

docker_run(){
  run "docker run \
    --interactive \
    --tty \
    --rm \
    -e 'TERM=xterm-256color' \
    -v $DOCKER_VOLUME:/mnt/steam/ \
    $DOCKER_IMAGE \
    $1"
}

docker_compose_maintenance(){
  run "docker-compose run maintenance $1"
}

docker_compose(){
  run "docker-compose $1"
}
